# 线上Docker Stack方式部署的启动文件
version: '3.7'

services:
  master:
    image: aaronzjc/mu:latest
    deploy:
      replicas: 1
    ports:
      - 7980:7980
    configs:
      - source: mu_config
        target: /app/conf/app.json

  node_1:
    image: aaronzjc/crawler:latest
    deploy:
      replicas: 1
    ports:
      - 7981:7990

  node_2:
    image: aaronzjc/crawler:latest
    deploy:
      replicas: 1
    ports:
      - 7982:7990

configs:
  mu_config:
    external: true