version: '3.7'

services:
  api:
    image: aaronzjc/mu-api:latest
    deploy:
      replicas: 3
    ports:
      - 6981:7980
    configs:
      - source: mu_config
        target: /app/conf/app.json

  commander:
    image: aaronzjc/mu-commander:latest
    deploy:
      replicas: 3
    ports:
      - 6971:7970
    configs:
      - source: mu_config
        target: /app/conf/app.json

  node_1:
    image: aaronzjc/mu-agent:latest
    deploy:
      replicas: 1
    ports:
      - 6991:7990

  node_2:
    image: aaronzjc/mu-agent:latest
    deploy:
      replicas: 1
    ports:
      - 6992:7990

configs:
  mu_config:
    external: true